Provider: aws
CheckID: "cloudwatch_log_metric_filter_vpc_alarm_configured"
CheckTitle: Ensure CloudWatch metric filters and alarms are configured for VPC changes.
CheckType:
  - Software and Configuration Checks
  - Industry and Regulatory Standards
  - CIS AWS Foundations Benchmark
ServiceName: cloudwatch
SubServiceName: ""
ResourceIdTemplate: arn:aws:logs:region:account-id:log-group:log-group-name
Severity: medium
ResourceType: AwsCloudWatchLogGroup
Description: Ensure CloudWatch metric filters and alarms are configured for VPC changes to monitor and alert on activities like VPC creation, deletion, or modification.
Risk:
  CloudWatch metric filters and alarms provide visibility into critical changes in the AWS environment. Without configuring them for VPC-related events, there could be a lack of awareness and response to unauthorized or unintentional VPC changes.
RelatedUrl: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Alarm-On-Logs.html
Remediation:
  Code:
    CLI:
      aws logs put-metric-filter --log-group-name <log-group-name> --filter-name <filter-name> --filter-pattern <pattern> --metric-transformations metricName=<metric-name>,metricNamespace=<namespace>,metricValue=<value>
    Other: https://docs.aws.amazon.com/athena/latest/ug/cloudwatch-logs.html
  Recommendation:
    Text:
      Ensure CloudWatch metric filters are in place for VPC creation, modification, and deletion events, and that alarms are set up to notify relevant stakeholders of any unauthorized or critical changes to VPC resources.
    Url: https://docs.aws.amazon.com/cloudwatchlogs/latest/APIReference/API_PutMetricFilter.html
Categories:
  - security
  - monitoring
DependsOn: []
RelatedTo: []
Notes: |
  This check ensures that CloudWatch metric filters and alarms are set up to monitor VPC-related changes. Without this, administrators may not be alerted to critical changes, such as the creation or deletion of VPCs, which could lead to security risks.
